-- DEPRECATED — jangan impor file ini.
--
-- Aplikasi memakai tabel:
--   arsip_surat      (metadata surat masuk/keluar)
--   surat_disposisi  (alur disposisi, termasuk awal Sub Admin E-Org → Kabag_organisasi)
--
-- Impor skema resmi:
--   install/arsip_surat_surat_disposisi.sql
--
-- Atau buka sekali di browser (Laragon):
--   /cek_db.php
-- Tabel dibuat otomatis lewat includes/surat_disposisi_db.php
